### PR TITLE
Fix price factors

### PR DESCRIPTION
**Pull request by alkuzman**
- Stock overview: API changed the qu_factor_purchase_to_stock is no longer available in product + plus use PriceQU instead of PurchaseQU
- Shopping list: the list entry always returns the amount in StockQU but the code assumes that it will change depending on the QU specified on the item.

This PR should close: #743, #742 and #757

### CODE REVIEW

**Review by dominiczedler — APPROVED** [review]
Thank you very much! I will change the stock overview part so that the compatibility will not be broken (else Grocy server versions below 4.0 won't work anymore). We would like to increase minimum version with the next big version, but not yet. So the compatibility is still a thing...

**Comment by alkuzman** [comment]
If you want, I will give it another try, but I have to try old servers to see what's missing. I guess the resolved conversions are the biggest issues.

**Comment by alkuzman** [comment]
If you have an old database, it would be great if you could share it.

**Comment by dominiczedler** [comment]
No this is fine I think, it makes no sense to support old versions for such a long time after release of newer versions. Additionally we don't have much time anyway, so it makes development and change of things harder for us...

**Pull request merged**
