### PR TITLE
WIP: Add Recipes

### PR DESCRIPTION
**Pull request by Tim-Otte**
Implements the feature requested in #148

### CODE REVIEW

**Comment by Tim-Otte** [comment]
Error [#1855](https://github.com/grocy/grocy/issues/1855) in grocy must be fixed for this feature to work correctly

**Comment by Tim-Otte** [comment]
Current state of development:
|  |  |
| -----------------------------------------------------------------------------|--------------------------------------------------------------------------------|
|  |  |

**Comment by MrJohnZoidberg** [comment]
Looks wonderful!

**Comment by MrJohnZoidberg** [comment]
After the initial work we should think about a grid view for recipes with pictures, with that we also should investigate whats the best way for handle image caching and downloading. 😄

**Comment by Tim-Otte** [comment]
Thats nice to hear!

At first I was not sure if I want to display the image in the bottom card and/or the first quarter of the list entry. But since there are no images displayed in the app, I decided to exclude the images for now.

For image caching I would recommend to get the HTTP header of the image file from the web server when the images are shown. If the request succeeds you can compare the [ETag header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) value with the value stored in the local database. If they are equal the image did not change, if they are different the image has to be updated.

The ingredients are currently not perfectly designed because there are no abbreviations for the quantity units. For something like Pack or Tin the design works perfectly but something like Mililitre is too long for the layout. Maybe this needs some attention of an android expert 😉

The only missing features for the linked issue are the possibility to add/edit ingredients and the mealplan.

**Comment by MrJohnZoidberg** [comment]
Okay nice, so do you want to finish these features or do you think we can merge the changes soon?

Thanks for the hints with the ETag, I will look into it soon. The DownloadHelper Class should be splitted into several classes first I think, this is a really ugly part of the code :) And then we can look how we manage the image caching after that.

**Comment by MrJohnZoidberg** [comment]
The HTML text or editor thing is another point which should be improved... That's the same thing like on the master product page the description which can also contain almost all HTML elements such as images, links and so on.
Today I've experimented with AztecEditor which is a HTML editor view from Wordpress for Android, maybe we can use that for these things. I still have to try if this module can simply display HTML code without editing (like we need on the product info or recipe bottom sheet). If it doesn't work we need some other module or solution for that.

**Comment by Tim-Otte** [comment]
> Okay nice, so do you want to finish these features or do you think we can merge the changes soon?

I would like to finish the recipe part of the issue (editing and adding ingredients) before merging the pull request. For the mealplan I can create a separate pull request if you wish.

**Comment by Tim-Otte** [comment]
I have an error in my code that I don't know how to fix:

The following code produces the error:
```java
binding.categoryQuantityUnit.setOnClickListener(v -> navigate(RecipeEditIngredientEditFragmentDirections
            .actionRecipeEditIngredientEditFragmentToMasterProductCatQuantityUnitFragment(viewModel.getAction())
            .setProduct(viewModel.getProduct())));
```

This is the error that is thrown while building the app:
```
...\grocy-android\app\src\main\java\xyz\zedler\patrick\grocy\fragment\RecipeEditIngredientEditFragment.java:96: error: method actionRecipeEditIngredientEditFragmentToMasterProductCatQuantityUnitFragment in class RecipeEditIngredientEditFragmentDirections cannot be applied to given types;
            .actionRecipeEditIngredientEditFragmentToMasterProductCatQuantityUnitFragment(viewModel.getAction())
            ^
  required: no arguments
  found: String
  reason: actual and formal argument lists differ in length
```

This is the source fragment definition:
```xml
    <fragment
      android:id="@+id/recipeEditIngredientEditFragment"
      android:name="xyz.zedler.patrick.grocy.fragment.RecipeEditIngredientEditFragment"
      android:label="RecipeEditIngredientEditFragment"
      tools:layout="@layout/fragment_recipe_edit_ingredient_edit">
    <deepLink
        android:id="@+id/deepLink18"
        app:uri="@string/deep_link_recipeEditIngredientEditFragment" />
    <argument
        android:name="action"
        app:argType="string" />
    <argument
        android:name="recipePosition"
        app:argType="xyz.zedler.patrick.grocy.model.RecipePosition"
        app:nullable="true"
        android:defaultValue="@null" />
    <argument
        android:name="startWithScanner"
        app:argType="boolean"
        android:defaultValue="false" />
    <argument
        android:name="closeWhenFinished"
        android:defaultValue="false"
        app:argType="boolean" />
    <action
        android:id="@+id/action_recipeEditIngredientEditFragment_to_masterProductCatQuantityUnitFragment"
        app:destination="@id/masterProductCatQuantityUnitFragment"
        app:enterAnim="@anim/slide_from_end"
        app:exitAnim="@anim/slide_to_start"
        app:popEnterAnim="@anim/slide_from_start"
        app:popExitAnim="@anim/slide_to_end" />
  </fragment>
```

This is the destination fragment definition: (already defined for the Master Product Page)
```xml
    <fragment
      android:id="@+id/masterProductCatQuantityUnitFragment"
      android:name="xyz.zedler.patrick.grocy.fragment.MasterProductCatQuantityUnitFragment"
      android:label="MasterProductCatQuantityUnitFragment"
      tools:layout="@layout/fragment_master_product_cat_quantity_unit">
      <argument
        android:name="product"
        app:argType="xyz.zedler.patrick.grocy.model.Product"
        app:nullable="true"
        android:defaultValue="@null" />
      <argument
        android:name="action"
        app:argType="string" />
    </fragment>
```

@patzly or @MrJohnZoidberg Do you know why this error is thrown? Android Studios syntax highlighting indicates no error. The error is only thrown while building the app.

**Comment by MrJohnZoidberg** [comment]
I will build your code now and try to fix it, I don't know yet what the issue could be...

**Comment by Tim-Otte** [comment]
Thank you <3

**Comment by patzly** [comment]
"required : no arguments" means that the .action...() doesn't have any arguments, navigation destinations given to the navigate() method are just the static action method without any arguments.

**Comment by Tim-Otte** [comment]
Yeah, that was my guess to, but then Android Studio thinks that an argument is missing...
image

**Comment by MrJohnZoidberg** [comment]
So, mal auf Deutsch hier kurz :-)

Das Problem ist, dass die MasterProduct Seiten in einem anderen Navigation graph liegen als dem Main navigation graph, wo die Recipe Seite liegt. Sichtbar ist das ja im grafischen Navigation Editor, wo die nested graphs erst angeklickt werden müssen, um die darin liegenden Navigationen anzuzeigen.
Ich habe seit dem Beginn mit den Navigation Components in der App im Internet keine Möglichkeit gefunden, mit dem SafeArgs Zeug (so wie du es gerade versuchst) zu einer Seite innerhalb eines anderen Navigation graphs zu kommen. Das geht meines Wissens nach nur mit Deeplinks, die in der values/deeplinks.xml hinterlegt sind. Das Problem bei Deeplinks ist aber, dass man nicht wie bei SafeArgs Objekte mit übergeben kann, sondern man kann nur IDs oder Strings übergeben wenn nötig.
Das heißt also, wenn man von der Recipe Seite jetzt zu der Master Product QuantityUnit Seite navigieren will, muss man auf die Objektübergabe verzichten und die IDs der Objekte benutzen (so wie die Argumente in den Deeplink URIs hinterlegt sind).

Also um nochmal den Fehler zusammenzufassen: Du hast wahrscheinlich nicht den grafischen Navigation editor verwendet, um diese Action zu erstellen, weil die QuantityUnits Seite ja nicht erreichbar ist von dem Main graph. Dann hast du stattdessen vermutlich die ID des Fragments per Code als Action hinzugefügt, das bringt die IDE aber irgendwie durcheinander und sagt dass ein Argument erforderlich ist, obwohl es stattdessen ohne ein Argument buildet (dann aber vermutlich beim Aufruf der Zeile abstürzt).

Jetzt zur Lösungsannäherung: Die MasterProduct Seiten basieren darauf, dass das Überprüfen und Speichern der Daten in der Übersichtsseite geschieht. Also du hast ja sicherlich gemerkt, dass wenn man in der QuantityUnits Kategorie das Produkt speichern will, die Übersichtsseite wieder erscheint und dann erst gespeichert wird, weil dort gesammelt auf Validität der Daten des Produkts geprüft werden kann.
Also ist es wahrscheinlich notwendig, mit dem schon vorhandenen Deeplink für die MasterProduct Übersichtsseite erst auf die Übersichtsseite zu navigieren und dann müssten wir eine Funktion einbauen, die ausgehend von einem zusätzlichen Argument dann zu einer Unterkategorie (in dem Fall QuantityUnits) automatisch navigiert. Der Code ist für den ersten Teil (vom ProductOverviewBottomSheet geklaut):
```java
navigateDeepLink(R.string.deep_link_masterProductFragment,
            new MasterProductFragmentArgs.Builder(Constants.ACTION.EDIT)
                .setProductId(productId).build().toBundle());
```
Da siehst du auch, dass nur die ProductId übergeben werden kann (ist zwar für schöneren Code hier mit SafeArgs gemacht wo theoretisch Objekte übergeben werden können, aber die Argumente werden in der navigateDeepLink Methode in die URI eingefügt, wo ja keine Objekte stehen können).
Das Navigieren zu der Kategorie würde ich persönlich jetzt erst mal weglassen, und das aber als TODO hinzufügen, damit ich die Funktion hinzufügen kann. Vielleicht bin ich aber schon nachher so motiviert, die Funktion reinzumachen, die ist nämlich schon auf der Settings Seite fast genau so drin.
So, ziemlich viel geschrieben, jetzt verstehst du das mit der Navigation hoffentlich etwas besser. :-)
Noch mehr Infos zu Deeplinks (fast so wie ich es implementier habe), stehen hier: https://oozou.com/blog/an-easy-way-to-use-deep-link-in-navigation-component-on-a-big-project-97

**Comment by MrJohnZoidberg** [comment]
Okay ich habe gerade deine Seiten ausprobiert, und jetzt frage ich mich, ob du das richtige vor hast... :-)

Du möchtest ja in der Zutaten-Bearbeiten Seite die QuantityUnits zum auswählen machen, so wie auf der Purchase Seite oder der ShoppingListItemEdit Seite... Warum möchtest du dann zu der MasterProductCatQuantityUnits Seite navigieren? Da ist doch das QuantityUnitsBottomSheet viel angebrachter, so wird es ja auch auf der Website gemacht... Ich sehe keine Notwendigkeit, warum man an dieser Stelle die QuantityUnits von dem Produkt bearbeiten wollen würde.

Also hast du gerade viel über Navigations in der App gelernt, was eigentlich gar nicht nötig gewesen wäre glaube ich. :-)

**Comment by Tim-Otte** [comment]
Oh no, peinlich...🥲
Der ganze Aufwand und ich habe auch noch ein falsches View anzeigen wollen...
Aber naja, ich habe wenigstens was über Navigation in Android gelernt. Den Blogeintrag dazu gucke ich mir auch Mal an.

Vielen lieben Dank für die Hilfe und die Erklärung. Wenn man da noch nicht so in der Materie ist, kann das schnell verwirrend werden 😐

Gerne, das Projekt macht wirklich Spaß!

**Comment by Tim-Otte** [comment]
Hey @patzly und @MrJohnZoidberg,

momentan komme ich leider nicht so oft zum Programmieren, wie ich es mir wünschen würde. Daher erst heute wieder ein Commit.

Ich habe eine Frage zum Ablauf beim Hinzufügen von Zutaten zu einem neuen Rezept. Wenn ich gerade ein Rezept erstelle und es noch nicht gespeichert habe, habe ich ja noch keine Id, unter der ich die Zutaten abspeichern kann. Wie bekomme ich beim Speichern einer Zutat diese zum Rezept, damit ich die Zutaten beim Speichern gesammelt hinzufügen kann? Oder gibt es eine andere Möglichkeit, die Zutaten abzuspeichern?

Momentan können bei existierenden Rezepten die Zutaten bearbeitet werden, weil die Änderungen ja auf dem Server bzw. in der lokalen DB gespeichert werden und dann in den anderen Views geladen werden können.

Vielen Dank schonmal für die Hilfe! ❤️

**Comment by MrJohnZoidberg** [comment]
Hey, lass dir die Zeit die du brauchst, das macht nichts. :)

Wenn du beim Server ein [neues Rezept erstellst](https://en.demo.grocy.info/recipe/new), kannst du unten auswählen, ob beim erstellen zurück navigiert werden soll oder auf der Seite geblieben werden soll. Das ist genau das Prinzip, wie beim Product erstellen (dort kann man danach ja auch noch Barcodes und Conversions hinzufügen). In unserer App kannst du es dir auch anschauen, da gibt es unten im Bottom menu so ein Speichersymbol mit einem Stift dran glaube ich, das sendet das Produkt auch an den Server und danach wird die Seite in "Produkt bearbeiten" umgewandelt, weil es die ID dann vom Server bekommen hat und alles damit machen kann.

Also genau so kann man auch beim Rezept erstellen vorgehen glaube ich.
Auf dem Server interface passiert beim Speichern diese Anfrage (Minimalbeispiel):
`POST: https://en.demo.grocy.info/api/objects/recipes`
```json
{
	"base_servings": "1",
	"description": "",
	"name": "abc",
	"not_check_shoppinglist": "0",
	"product_id": ""
}
```
Response:
```json
{
	"created_object_id": "8"
}
```
Diese objectId kannst du dann wie in den schon vorhandenen Produkt ViewModels verarbeiten bzw verwenden zum Editieren der Sachen.
Zum Hinzufügen von Zutaten, würde ich sagen, ist es wie beim Produkt und den Barcodes oder Conversions nötig, das Rezept erst auf den Server zu laden und dann die Id zurückzubekommen. Also das wäre meiner Ansicht nach die beste Möglichkeit, anstatt alles irgendwie zwischenzuspeichern und am Ende dann einen Haufen Anfragen an den Server machen zu müssen.
:heart:

**Comment by Tim-Otte** [comment]
Hey zusammen,

danke für die Hilfe. ❤️

Habe mir den entsprechenden Vorgang zum Anlegen von Produkten angeguckt und bei den Rezepten so übernommen. Das Hinzufügen / Bearbeiten von Zutaten ist nun nur noch möglich, wenn das Rezept auf den Server übertragen wurde.

Ich muss das Feature noch ein wenig auf Fehler überprüfen und noch edge cases austesten, aber insgesamt ist diese PR soweit fertig und daher auch "Ready for review". Anmerkungen zum Code gerne mir schicken, damit ich daraus lernen kann.

Ansonsten: Hat Spaß gemacht und ich freue mich, sobald ich wieder mehr Zeit habe, auf die nächste PR 😊

**Review by MrJohnZoidberg — APPROVED** [review]
Habe keine schlechten Sachen gefunden :-)
Ein paar kleine Dinge, die mir aufgefallen sind, passe ich nach dem Merge an.

**Comment by MrJohnZoidberg** [comment]
Du kannst entweder sagen, wenn dir noch etwas auffällt oder nochmal einen Merge request machen, wenn es etwas größeres ist. 

Danke für deinen großen Beitrag zu der App! :heart:

**Comment by Tim-Otte** [comment]
Hey, das ist ja schön zu hören. Ich bin gerade in Bayern im Urlaub und habe (leider) nicht das technische Equipment dabei, um die App zu testen und zu überarbeiten. Falls mir daheim was auffällt, melde ich mich gerne nochmal.

Habe ich gerne gemacht, hat viel Spaß gemacht! Wenn ich nochmal Zeit habe, kümmere ich mich gerne um weitere Features. ❤️

**Comment by MrJohnZoidberg** [comment]
Sehr cool, danke für das Angebot!
Genieße deinen Urlaub, alles andere kommt danach. :smile:

**Comment by simonsan** [comment]
Danke euch! @MrJohnZoidberg @Tim-Otte

Tolle Arbeit!

**Comment by MrJohnZoidberg** [comment]
Danke für deine Wertschätzung, ist immer schön zu hören!
Die neue Version kommt in ein paar Tagen dann mal wirklich, war jetzt schon viel zu lange kein Update mehr wegen Leben abseits des Computers und weil noch an paar Sachen geschliffen wurde...

**Pull request merged**
