### PR TITLE
Add Task list

### PR DESCRIPTION
**Pull request by mcbloch**

### CODE REVIEW

**Comment by MrJohnZoidberg** [comment]
Wow, you worked a lot for this! I hope our code wasn't too bad for you.
You can write me if you want me to finish your work or if you have any questions.

**Comment by mcbloch** [comment]
> Wow, you worked a lot for this! I hope our code wasn't too bad for you.
> You can write me if you want me to finish your work or if you have any questions.

The code is actually pretty clean and well structured. It was easy to understand the flows and I was very happy to work on it.
I'm glad the contribution is welcomed :). I am not at all done tho, I actually wanted to make a pr to my own repository to get an overview of the changes, but I clicked to fast and didn't see it defaults to the upstream repository.

My main question would be how you see this feature visually. My idea atm: 
- **Main page**: It has the stock overview, shopping list, en then a grid of the 4 main stock action buttons. Because tasks is not the only missing part, but chore-lists, batteries and equipment are also mentioned I thought these would fit in its own grid above the Master Data. With only tasks I would make it full width like the shopping list and later on you could move to the grid.
- **Task list**: I think the shopping list has the exact style you want from a task list. 
  - I see the `chips` useful to filter _due_ and _overdue_ tasks and would like to be able to filter _todo_ and _done_ as well. The code however uses chips as exclusive filters and I think you would want to combine these 4 as todo and overdue is a sensible combo. Maybe you have a good suggestion for this. (I don't want to change the behavior of the chips as this would have an unexpected effect for users resulting in bad UX)
  - The + button and search would be very usefull.
  - Task categories could be used just like the product groups, grouping tasks in the list per category, putting the ones without category on the bottom as 'Uncategorized'. I think however that this could be unwieldy when you have a lot of tasks. A filter behind the 3 dots would be a safe option but with the absence of separate task lists I think you could reuse the dropdown used for shopping lists as a dropdown for task categories. You then also get a handy UI to edit, delete and add categories reusing the shopping lists flow. A static _all-categories_ or _clear-category-filters_ option would be necessary then. Bonus question: would multi select be better then single select or just more confusing (for task categories when using it in the dropdown).

What are your thoughts on this? Do you agree on some or most parts, what would you do differently?

Reviewing the code would not be very useful atm because it's still a mess, but will definitely be useful in the future to be sure I don't break anything else. If you want I can give you an @ for that if I think it's review ready, so I don't waste your time.

**Comment by MrJohnZoidberg** [comment]
The new filter implementation is in master now, it is really easy to implement on a new page compared to the old filter row within RecyclerView. I hope you like it.

**Comment by MrJohnZoidberg** [comment]
@mcbloch I've copied your edited files and I've almost finished the functionality (additional fragment with form). Thanks for your work! :)
I did not merge your work because there were conflicts and I didn't manage to resolve them in Android Studio or cli, sorry.

**Comment by mcbloch** [comment]
I'm sorry that I didn't come to finishing the feature. I did like to finish it, but eventually did not find the time to do it. 
No problem about not merging it! I'm happy it's being worked on and I can't wait to see the result.

**Pull request closed without merging**
