### PR TITLE
Update StockFragment.java

### PR DESCRIPTION
**Pull request by donk7413**
Fix for #119
I make a addition of the current amount of the stock item and the current Aggredated amount for the current item then if the currentamount is under the stock item's product minium amount, I add it to the missingStockItems list

### CODE REVIEW

**Comment by donk7413** [comment]
Tested on my own phone and with similar parameters described in #117 => the items doens't show as missing in list.

**Comment by donk7413** [comment]
TO DO : 
make a method to get recursively the total amount for a parent with childrens than contains childrens too. For now is just one parent one children layer.

**Comment by MrJohnZoidberg** [comment]
Thank you for your work!
It's a good solution for the current code, but I have just worked on this part and made it less dirty than it was before. Now it takes
simply all items which are in missingItems from volatile request and there is more linear logic in the code now.

Sorry I will close this MR, but we appreciate your work.

**Comment by MrJohnZoidberg** [comment]
Can you please test the current master branch?

**Comment by donk7413** [comment]
I will test it Monday and keep you in touch. After discussing with grocy devs, there is actually no plan to implement 3 layers tree. So if your solution is already operationnal, there is no reason to keep mine. Actually I think the "less dirty" way is server data drives. Means the using volatile. So it's ok for me. I will try the latest master Monday 🙂

**Comment by MrJohnZoidberg** [comment]
Ok, thank you! I will try the filtering for myself with a few products. If it has no bugs anymore and behaves like the web server, we will maybe release v1.9.0 today evening and if you find a bug, we can then publish v1.9.1 as soon as we fixed that bug. :+1:

**Comment by donk7413** [comment]
Great, ok for me. I will use my grocy this weekend with big import (70000+ recipes) so I can test stress usage and behavior

**Pull request closed without merging**
