### PR TITLE
improve formatting of fastlane app description

### PR DESCRIPTION
**Pull request by IzzySoft**
Looks nicer when rendered :wink: Besides, you could also remove images from `de-DE` if they are identical to those in `en-US` (currently it seems they all are); what's not there in one language should be taken from `en-US`, which usually serves as fallback.

### CODE REVIEW

**Comment by MrJohnZoidberg** [comment]
Thanks a lot! I already donated some money for your work a few weeks ago. :-)

**Comment by IzzySoft** [comment]
Yes, thanks for that as well! :green_heart:

Btw: I've now set metadata for your app in my repo to fetch "title,shortdesc,fulldesc,icon" from your Fastlane, so updates will be reflected with each new version (other than F-Droid, my updater fetches Fastlane from `HEAD`). Should you decide to "clean-up" screenshots as well, please let me know, so I add to have them fetched along.

**Comment by IzzySoft** [comment]
That was fast… :rofl: Thanks again!

**Comment by IzzySoft** [comment]
OK, all updated. Now automatically fetching with each new release: "title,shortdesc,fulldesc,changelogs,icon,featureGraphic,screenshotsJPG" (last one means, updater converts them to JPG to save some space/xfer, makes loading faster in the client).

**Comment by MrJohnZoidberg** [comment]
Thanks, that's great! Am I right if I say that our [issue](https://gitlab.com/fdroid/rfp/-/issues/1477) in the RFP repo will be open for the next months or even years? Because I see 330 issues and some of them are very old.

**Comment by IzzySoft** [comment]
It might be processed tomorrow, next week or later – that's hard to say. Our packagers do not process RFPs chronologically. If it was not picked up within 2 weeks or more after I've added the "ready" label, feel free to ping it – I'd then forward the ping to some of our packagers (ouch, 3+ weeks already – I've just sent that ping). That has a 50:50 chance of speeding up things. For an 80:20 chance, open the corresponding MR yourself; especially if you can point out it builds with fdroidserver, as that would even increase chances to 90:10 that it will be merged quickly.

**Comment by MrJohnZoidberg** [comment]
Ah, I understand. I think it's currently too much work for me to set up an fdroidserver or create a MR – so I will be patient and wait for a packager (inclusion is not urgent, just would be great).
Thanks for the infos and the ping on gitlab.:smile:

**Comment by IzzySoft** [comment]
Your app is welcome to my repo for as long as you wish it to stay there. That includes after F-Droid has picked it up if you want (e.g. to have pre-releases in my repo and stables in F-Droid – some projects have it that way) – but that you'd need to explicitly say then, as otherwise I usually remove apps a week or so after they were published "over there".

**Comment by IzzySoft** [comment]
So, "that RFP" was processed now \o/ Which means your app should show up at F-Droid soon – at which point I usually remove it from my repo, unless you want me to keep it for some reason?

**Comment by MrJohnZoidberg** [comment]
I think you can remove it from your repo now. Thanks a lot for all your work:clap:

One last question: How is F-Droid's behaviour when I publish a pre-release with "-beta" at the end (in the tag and versionName). Will it be published in F-Droid as well?

**Comment by IzzySoft** [comment]
Nope, F-Droid would ignore that as it doesn't match the tag name pattern specified. That's how we distinguish things with some apps: F-Droid picks up only the stables, and my updater only picks up the "-beta". Note that nevertheless, you could not cross-update (due to different signature). But if the beta would also use a different package name (like, also having `.beta` appended), both could be used in parallel.

PS: And I won't remove the app before it shows up in F-Droid's index. So you still have some time to re-decide :smile:

**Pull request merged**
